### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by georgeperez** [dandv/convert-chrome-cookies-to-netscape-format#1]
Not really a node dev, so not sure what I need to fix here. Any idea?

<img width="805" alt="Screen Shot 2020-03-30 at 12 48 06 PM" src="https://user-images.githubusercontent.com/8184356/77939187-c5eb4080-7284-11ea-943f-2408912151f9.png">

**Comment by dandv** [comment]
Sorry, I completely missed this. How did you solve the issue?

**Comment by zachary** [comment]
The same issue, please let me know how to resolve it. thanks

**Comment by spencermwoo** [comment]
EDIT : nevermind.  The issue is that it's difficult to copy all cookie text

Solution is to properly copy all cookies into a file.  Your `file-with-cookies-copy-pasted-from-Chrome.txt` is not the full copy of the page https://github.com/dandv/convert-chrome-cookies-to-netscape-format/blob/master/chrome-cookies.png
